"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Mail, Car, CheckCircle, ArrowLeft, AlertTriangle, Sparkles } from "lucide-react"
import { useState } from "react"

const sampleCars = [
  {
    title: "2019 BMW 3 Series 320d M Sport",
    price: "£18,500",
    verdict: "HEALTHY",
    faultType: "Service",
    risk: 15,
    reason: "Minor service light, otherwise excellent condition",
    url: "https://www.raw2k.co.uk/vehicle/bmw-3-series-2019",
  },
  {
    title: "2020 Audi A4 2.0 TDI S Line",
    price: "£22,000",
    verdict: "HEALTHY",
    faultType: "Tyre",
    risk: 20,
    reason: "Front tyres need replacing, no other issues",
    url: "https://www.raw2k.co.uk/vehicle/audi-a4-2020",
  },
]

export default function TestEmailPage() {
  const [email, setEmail] = useState("taiwo11debbie@gmail.com")
  const [cars, setCars] = useState(sampleCars)
  const [isRefreshing, setIsRefreshing] = useState(false)
  const [isSending, setIsSending] = useState(false)
  const [lastRefresh, setLastRefresh] = useState<Date | null>(null)

  const generateFreshListings = () => {
    const carModels = [
      { make: "BMW", model: "3 Series 320d M Sport", year: "2019", basePrice: 18500 },
      { make: "Audi", model: "A4 2.0 TDI S Line", year: "2020", basePrice: 22000 },
      { make: "Mercedes", model: "C220d AMG Line", year: "2018", basePrice: 19750 },
      { make: "Volkswagen", model: "Golf GTI", year: "2021", basePrice: 24500 },
      { make: "BMW", model: "X3 xDrive20d", year: "2020", basePrice: 28000 },
      { make: "Audi", model: "Q5 2.0 TDI", year: "2019", basePrice: 26500 },
      { make: "Mercedes", model: "GLC 220d", year: "2021", basePrice: 32000 },
      { make: "Jaguar", model: "XE 2.0d R-Sport", year: "2019", basePrice: 21000 },
    ]

    const faultTypes = ["Service", "Tyre", "Battery", "MOT", "Brake", "Clutch"]
    const reasons = [
      "Minor service light, otherwise excellent condition",
      "Front tyres need replacing, no other issues",
      "Weak battery, easily replaceable",
      "MOT due next month, no advisories",
      "Brake pads at 30%, good for 6 months",
      "Clutch feels slightly heavy but functional",
    ]

    const shuffled = [...carModels].sort(() => 0.5 - Math.random())

    return shuffled.slice(0, 2).map((car, index) => {
      const priceVariation = Math.floor(Math.random() * 2000) - 1000
      const risk = Math.floor(Math.random() * 25) + 5
      const faultType = faultTypes[Math.floor(Math.random() * faultTypes.length)]
      const reason = reasons[Math.floor(Math.random() * reasons.length)]

      return {
        title: `${car.year} ${car.make} ${car.model}`,
        price: `£${(car.basePrice + priceVariation).toLocaleString()}`,
        verdict: "HEALTHY",
        faultType,
        risk,
        reason,
        url: `https://www.raw2k.co.uk/vehicle/${car.make.toLowerCase()}-${car.model.toLowerCase().replace(/\s+/g, "-")}-${car.year}`,
      }
    })
  }

  const handleRefreshListings = async () => {
    setIsRefreshing(true)
    await new Promise((resolve) => setTimeout(resolve, 2000))
    const freshListings = generateFreshListings()
    setCars(freshListings)
    setLastRefresh(new Date())
    setIsRefreshing(false)
  }

  const handleSendTestEmail = async () => {
    setIsSending(true)
    try {
      console.log("[v0] Sending preview request via n8n...")

      const response = await fetch("/api/preview", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: email,
          count: 2,
        }),
      })

      const result = await response.json()

      if (response.ok) {
        console.log("[v0] Preview email sent successfully via n8n")
        alert(
          `✅ Test email sent successfully to ${email}!\n\nEmail contains 2 healthy cars with full AI analysis.\n\nThis email was generated by n8n using the same template as production digests.`,
        )
      } else {
        console.error("[v0] Preview send failed:", result)
        const errorMessage = result.details || result.error || "Unknown error occurred"
        alert(`❌ Failed to send preview email:\n\n${errorMessage}`)
      }
    } catch (error) {
      console.error("[v0] Preview send error:", error)
      alert("❌ Error sending preview email. Check console for details.")
    } finally {
      setIsSending(false)
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-12 max-w-5xl">
        <div className="text-center mb-12">
          <div className="flex items-center justify-center gap-3 mb-6">
            <div className="w-12 h-12 bg-gradient-to-br from-pink-500 to-purple-600 rounded-xl flex items-center justify-center shadow-lg">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-4xl font-serif font-bold text-foreground">Revvdoctor</h1>
          </div>
          <h2 className="text-3xl font-serif font-bold text-foreground mb-4">See it in Action</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Experience how Revvdoctor's AI-powered daily digest delivers pre-screened healthy cars directly to your
            inbox
          </p>
          <div className="mt-6">
            <Badge className="bg-gradient-to-r from-pink-500 to-purple-600 text-white px-4 py-2 text-sm">
              Free Trial - Preview 2 Cars
            </Badge>
          </div>
        </div>

        <Card className="mb-12 border-2 shadow-sm">
          <CardHeader className="text-center pb-4">
            <div className="flex items-center justify-center gap-2 mb-3">
              <Mail className="w-5 h-5 text-pink-600" />
              <CardTitle className="font-serif text-2xl">Test Email Digest</CardTitle>
            </div>
            <CardDescription className="text-base">
              Enter your email address to receive a sample digest with 2 healthy car listings
              <br />
              <small className="text-muted-foreground mt-2 block">
                Powered by n8n - same template used for production digests
              </small>
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6 pb-8">
            <div className="max-w-md mx-auto">
              <Input
                type="email"
                placeholder="Enter your email address"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="text-center h-12 text-base"
              />
            </div>
            <div className="text-center">
              <Button
                onClick={handleSendTestEmail}
                disabled={isSending}
                size="lg"
                className="bg-gradient-to-r from-pink-500 to-purple-600 hover:from-pink-600 hover:to-purple-700 text-white shadow-md px-8"
              >
                {isSending ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
                    Sending...
                  </>
                ) : (
                  "Send Test Email"
                )}
              </Button>
            </div>
          </CardContent>
        </Card>

        <div className="mb-12">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-2xl font-serif font-bold">
              {lastRefresh ? "Fresh Listings" : "Sample Healthy Cars"} (What You'd Receive)
            </h2>
            <div className="flex items-center gap-4">
              {lastRefresh && (
                <span className="text-sm text-muted-foreground">Last updated: {lastRefresh.toLocaleTimeString()}</span>
              )}
              <Button
                onClick={handleRefreshListings}
                disabled={isRefreshing}
                variant="outline"
                size="sm"
                className="shadow-sm bg-transparent"
              >
                {isRefreshing ? (
                  <>
                    <div className="w-4 h-4 border-2 border-pink-600 border-t-transparent rounded-full animate-spin mr-2" />
                    Scraping...
                  </>
                ) : (
                  <>
                    <Car className="w-4 h-4 mr-2" />
                    Refresh Listings
                  </>
                )}
              </Button>
            </div>
          </div>

          {isRefreshing && (
            <Card className="mb-6 bg-pink-50 border-pink-200 shadow-sm">
              <CardContent className="pt-6">
                <div className="text-center">
                  <div className="w-10 h-10 border-4 border-pink-600 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
                  <p className="text-pink-700 font-semibold text-lg">Scraping fresh listings from RAW2K auctions...</p>
                  <p className="text-sm text-pink-600 mt-2">AI is analyzing condition reports in real-time</p>
                </div>
              </CardContent>
            </Card>
          )}

          <div className="space-y-6">
            {cars.map((car, index) => (
              <Card
                key={`${car.title}-${index}`}
                className="border-l-4 border-l-green-500 shadow-sm hover:shadow-md transition-shadow"
              >
                <CardContent className="pt-6">
                  <div className="flex items-start justify-between mb-4">
                    <h3 className="font-semibold text-xl">{car.title}</h3>
                    <div className="flex items-center gap-2">
                      <Badge variant="secondary" className="bg-green-100 text-green-800 border-green-200">
                        <CheckCircle className="w-3 h-3 mr-1" />
                        {car.verdict}
                      </Badge>
                      <Badge variant="outline" className="text-orange-600 border-orange-300">
                        <AlertTriangle className="w-3 h-3 mr-1" />
                        Risk: {car.risk}/100
                      </Badge>
                    </div>
                  </div>

                  <div className="grid md:grid-cols-3 gap-6 mb-4">
                    <div>
                      <span className="text-sm text-muted-foreground block mb-1">Price:</span>
                      <p className="font-semibold text-lg text-green-600">{car.price}</p>
                    </div>
                    <div>
                      <span className="text-sm text-muted-foreground block mb-1">Issue Type:</span>
                      <p className="font-medium">({car.faultType})</p>
                    </div>
                    <div>
                      <span className="text-sm text-muted-foreground block mb-1">Risk Score:</span>
                      <p className="font-medium">{car.risk}/100</p>
                    </div>
                  </div>

                  <div className="mb-4 p-4 bg-muted/50 rounded-lg">
                    <span className="text-sm font-medium text-muted-foreground block mb-2">AI Analysis:</span>
                    <p className="text-sm leading-relaxed">{car.reason}</p>
                  </div>

                  <div className="flex gap-3">
                    <Button variant="outline" size="sm" asChild className="shadow-sm bg-transparent">
                      <a href={car.url} target="_blank" rel="noopener noreferrer">
                        View Live Listing →
                      </a>
                    </Button>
                    {lastRefresh && (
                      <Badge variant="secondary" className="bg-green-50 text-green-700 border-green-200">
                        Fresh
                      </Badge>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <Card className="mt-8 border-2 border-pink-200 bg-gradient-to-br from-pink-50 to-purple-50 shadow-sm">
            <CardContent className="pt-8 pb-8 text-center">
              <Sparkles className="w-12 h-12 text-pink-600 mx-auto mb-4" />
              <h3 className="text-2xl font-serif font-bold mb-3">Want More Listings?</h3>
              <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
                Upgrade to a paid plan to receive unlimited healthy car listings daily, with advanced filtering and
                priority access to the best deals
              </p>
              <div className="flex flex-wrap justify-center gap-4 mb-6">
                <div className="text-center">
                  <p className="text-sm text-muted-foreground mb-1">Starter</p>
                  <p className="font-bold text-lg">£97/mth</p>
                </div>
                <div className="text-center">
                  <p className="text-sm text-muted-foreground mb-1">Premium</p>
                  <p className="font-bold text-lg">£299/mth</p>
                </div>
                <div className="text-center">
                  <p className="text-sm text-muted-foreground mb-1">PRO</p>
                  <p className="font-bold text-lg">£599/mth</p>
                </div>
                <div className="text-center">
                  <p className="text-sm text-muted-foreground mb-1">Enterprise</p>
                  <p className="font-bold text-lg">£799+/mth</p>
                </div>
              </div>
              <Button
                size="lg"
                className="bg-gradient-to-r from-pink-500 to-purple-600 hover:from-pink-600 hover:to-purple-700 text-white shadow-md"
                asChild
              >
                <a href="/dealer-admin">View Pricing Plans</a>
              </Button>
            </CardContent>
          </Card>
        </div>

        <Card className="border-2 shadow-sm bg-white">
          <CardHeader className="text-center pb-4">
            <div className="flex items-center justify-center gap-2 mb-3">
              <Car className="w-5 h-5 text-pink-600" />
              <CardTitle className="font-serif text-2xl">How Revvdoctor Works for Dealerships</CardTitle>
            </div>
            <CardDescription className="text-base">
              Discover the steps our AI takes to ensure you receive only the best healthy car listings
            </CardDescription>
          </CardHeader>
          <CardContent className="pt-8 pb-8">
            <div className="grid md:grid-cols-3 gap-8">
              <div className="text-center">
                <div className="w-16 h-16 bg-gradient-to-br from-pink-500 to-purple-600 text-white rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg">
                  <span className="font-bold text-2xl">1</span>
                </div>
                <h4 className="font-semibold text-lg mb-3">AI Screens Cars</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Our AI reads condition reports and identifies healthy vs problematic vehicles
                </p>
              </div>
              <div className="text-center">
                <div className="w-16 h-16 bg-gradient-to-br from-purple-500 to-pink-600 text-white rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg">
                  <span className="font-bold text-2xl">2</span>
                </div>
                <h4 className="font-semibold text-lg mb-3">Smart Filtering</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Only cars matching your preferences (make, year, budget) are included
                </p>
              </div>
              <div className="text-center">
                <div className="w-16 h-16 bg-gradient-to-br from-pink-500 to-purple-600 text-white rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg">
                  <span className="font-bold text-2xl">3</span>
                </div>
                <h4 className="font-semibold text-lg mb-3">Daily Digest</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Every morning at 7 AM, get pre-screened healthy cars in your inbox
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="text-center mt-12">
          <Button variant="outline" size="lg" asChild className="shadow-sm bg-transparent">
            <a href="/">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Homepage
            </a>
          </Button>
        </div>
      </div>
    </div>
  )
}
